ravitandon90/Code-Submissions

Ayush-Gupta/804. Unique Morse Code Words.cpp
Leetcode Problem Link: https://leetcode.com/problems/unique-morse-code-words/
=> 804. Unique Morse Code Words

Vindeep-Chaudhari/1863_Sum_of_All_Subset_XOR_Totals.cpp
Leetcode Problem Link - https://leetcode.com/problems/sum-of-all-subset-xor-totals/
=> 1863. Sum of All Subset XOR Totals

Ayush-Gupta/1338. Reduce Array Size to The Half.cpp
Leetcode Problem Link: https://leetcode.com/problems/reduce-array-size-to-the-half/
=> 1338. Reduce Array Size to The Half

Vindeep-Chaudhari/242._Valid_Anagram.cpp
Problem link - https://leetcode.com/problems/valid-anagram/
=> Day 2: 242. Valid Anagram

Ayush-Gupta/659. Split Array into Consecutive Subsequences.cpp
Leetcode Problem Link: https://leetcode.com/problems/split-array-into-consecutive-subsequences/
=> 659. Split Array into Consecutive Subsequences

clmathuriya/Day1Trie.java
=> clmathuriya - Day1 Trie Solution

satyam-sundaram/19-08-22/design-a-trie.go
=> [19Aug22] Design a Trie

Vindeep-Chaudhari/208_Implement_Trie_Prefix_Tree.cpp
Problem Link - https://leetcode.com/problems/implement-trie-prefix-tree/
=> 208. Implement Trie (Prefix Tree)

Ayush-Gupta/871. Minimum Number of Refueling Stops.cpp
Leetcode Problem Link: https://leetcode.com/problems/minimum-number-of-refueling-stops/
=> 871. Minimum Number of Refueling Stops

Vindeep-Chaudhari/1710_Maximum_Units_on_a_Truck.cpp, Vindeep-Chaudhari/208_Implement_Trie_Prefix_Tree.cpp
Problem Link - https://leetcode.com/problems/maximum-units-on-a-truck/
=> 1710. Maximum Units on a Truck

Vindeep-Chaudhari/1539_Kth_Missing_Positive_Number.cpp
Problem Link - https://leetcode.com/problems/kth-missing-positive-number/
=> 1539. Kth Missing Positive Number

Ayush-Gupta/342. Power of Four.cpp, Ayush-Gupta/936. Stamping The Sequence.cpp
LeetCode Problem Link: https://leetcode.com/problems/stamping-the-sequence/
=> 936. Stamping The Sequence

Vindeep-Chaudhari/1232_Check_If_It_Is_a_Straight_Line
Problem Link - https://leetcode.com/problems/check-if-it-is-a-straight-line/
=> 1232. Check If It Is a Straight Line

Ayush-Gupta/234. Palindrome Linked List.cpp
LeetCode Problem Link: https://leetcode.com/problems/palindrome-linked-list/
=> 234. Palindrome Linked List

Ayush-Gupta/21. Merge Two Sorted Lists.cpp, Ayush-Gupta/326. Power of Three.cpp
=> Merge Two Sorted List

Ayush-Gupta/274. H-Index.cpp
LeetCode Problem Link: https://leetcode.com/problems/h-index/
=> 274. H-Index

Vindeep-Chaudhari/721_Accounts_Merge.cpp
Problem Link - https://leetcode.com/problems/accounts-merge/
=> Vindeep: 721. Accounts Merge

Vindeep-Chaudhari/274_H-Index.cpp
Problem Link - https://leetcode.com/problems/h-index/
=> Vindeep : 274. H-Index

Ayush-Gupta/674. Longest Continuous Increasing Subsequence.cpp
Leetcode Problem Link: https://leetcode.com/problems/longest-continuous-increasing-subsequence/
=> 674. Longest Continuous Increasing Subsequence

Ayush-Gupta/88. Merge Sorted Array.cpp
LeetCode Problem Link: https://leetcode.com/problems/merge-sorted-array/
TC - O(n+m) | SC - O(1)
=> 88. Merge Sorted Array

Vindeep-Chaudhari/1460_Make_Two_Arrays_Equal_by_Reversing_Sub-arrays.cpp, Vindeep-Chaudhari/674_Longest_Continuous_Increasing_Subsequence.cpp, Vindeep-Chaudhari/88_Merge_Sorted_Array.cpp
88. Merge Sorted Array [Problem link]- https://leetcode.com/problems/merge-sorted-array/
1460. Make Two Arrays Equal by Reversing Sub-arrays [Problem link] - https://leetcode.com/problems/make-two-arrays-equal-by-reversing-sub-arrays/
674. Longest Continuous Increasing Subsequence [Problem link] - https://leetcode.com/problems/longest-continuous-increasing-subsequence/
=> Vindeep: 674. Longest Continuous Increasing Subsequence, 88. Merge Sorted Array, 1460. Make Two Arrays Equal by Reversing Sub-arrays

Sushant_Agawane/add_to_arr.cpp, Sushant_Agawane/arr_intersect_2.cpp, Sushant_Agawane/arr_intersection.cpp
Solved question on array today I have started 300 days of code Challenge.
=> array question

Lokesh_Saana/88. Merge Sorted Array.py
Code of the Day is added
Lokesh_Saana/88. Merge Sorted Array.py
Please review
=> Lokesh_Saana/88. Merge Sorted Array.py

Vindeep-Chaudhari/160_Intersection_of_Two_Linked_Lists.cpp
Problem Link - https://leetcode.com/problems/intersection-of-two-linked-lists/
=> Vindeep : 160. Intersection of Two Linked Lists

K_A_Rahim/Merge_Sorted_Array_88.java
This is 30th August problem (leetcode 88) from my side
=> adding for leetcode 88

Ayush-Gupta/217. Contains Duplicate.cpp, Ayush-Gupta/48. Rotate Image.cpp
LeetCode Problem Link : https://leetcode.com/problems/contains-duplicate/
TC : O(n)
=> 217. Contains Duplicate

krishna-kaushik/30thAug-Nested List Weight Sum.py
https://leetcode.com/problems/nested-list-weight-sum/ Leetcode problem DFS solution
=> Nested List Weight Sum problem solution - LC 339

Lokesh_Saana/11. Container With Most Water.py
=> Lokesh_Saana/11. Container With Most Water.py added

Lokesh_Saana/66-plus-one.py
=> Lokesh_Saana/66-plus-one.py

Ayush-Gupta/66. Plus One.cpp
LeetCode Problem Link: https://leetcode.com/problems/plus-one/
=> 66. Plus One

Lokesh_Saana/238-product-of-array-except-self.py
=> Lokesh_Saana/238-product-of-array-except-self.py

krishna-kaushik/1stSep- Range Sum Query - Mutable.py
https://leetcode.com/problems/range-sum-query-mutable/ python solution segment tree
=> range-sum-query-mutable LC 307 solution

Lokesh_Saana/1448-count-good-nodes-in-binary-tree.py, Lokesh_Saana/307-range-sum-query-mutable.py
=> Code of the day

K_A_Rahim/FizzBuzz_LC_412_easy.java
LC 412 easy submission on 1st September 2022
=> submission for leetcode 412 easy

Ayush-Gupta/238. Product of Array Except Self.cpp, Ayush-Gupta/307. Range Sum Query - Mutable.cpp
LeetCode Problem Link: https://leetcode.com/problems/product-of-array-except-self/
TC - O(n) | SC - O(n)
=> 238. Product of Array Except Self

Harish-Kumar/duplicate-in-sorted-array.java, Harish-Kumar/product-array-except-itself.java, Harish-Kumar/rotate-array-right.java
I have solved product of array except self and rotate array right problems
=> new porblem from harish-kumar

Lokesh_Saana/189-rotate-array.py
=> Lokesh_Saana/189-rotate-array.py is added

K_A_Rahim/Running_Sum_of_1d_Array_LC_1480_Easy.java
3rd September ,2022 submission
=> leetcode 1480 easy submission

Ayush-Gupta/189. Rotate Array.cpp
LeetCode Problem Link: https://leetcode.com/problems/rotate-array/submissions/
=> 189. Rotate Array

Vindeep-Chaudhari/184_Implement_strStr().cpp
Problem link - https://leetcode.com/problems/implement-strstr/
=> Vindeep : 184. Implement strStr()

K_A_Rahim/Number_of_Good_Pairs_LC_1512_Easy.java
This is for leetcode 1512 submission 4th September
=> This is for leetcode 1512 submission

Ayush-Gupta/1480. Running Sum of 1d Array.cpp
LeetCode Problem Link: https://leetcode.com/problems/running-sum-of-1d-array/
=> 1480. Running Sum of 1d Array

Lokesh_Saana/905-sort-array-by-parity.py
=> Lokesh_Saana/905-sort-array-by-parity.py is added

Ayush-Gupta/848. Shifting Letters.cpp
LeetCode Problem Link: https://leetcode.com/problems/shifting-letters/
=> 848. Shifting Letters

Ayush-Gupta/905. Sort Array By Parity.cpp
=> 905. Sort Array By Parity

Vindeep-Chaudhari/23_Merge_k_Sorted_Lists.cpp
Problem Link - https://leetcode.com/problems/merge-k-sorted-lists/
=> Vindeep : 23. Merge k Sorted Lists

Lokesh_Saana/1636-sort-array-by-increasing-frequency.py
=> Lokesh_Saana/1636-sort-array-by-increasing-frequency.py is added

Vindeep-Chaudhari/767_Reorganize_String.cpp
Problem Link - https://leetcode.com/problems/reorganize-string/
=> Vindeep : 767. Reorganize String

Lokesh_Saana/414-third-maximum-number.py
=> Lokesh_Saana/414-third-maximum-number.py is added

Lokesh_Saana/986-interval-list-intersections.py
=> Lokesh_Saana/986-interval-list-intersections.py is added

.vscode/settings.json, Vindeep-Chaudhari/1636_Sort_Array_by_Increasing_Frequency.cpp, Vindeep-Chaudhari/414_Third_Maximum_Number.cpp
Problem Link - https://leetcode.com/problems/sort-array-by-increasing-frequency/
=> Vindeep : 1636. Sort Array by Increasing Frequency

Ayush-Gupta/1636. Sort Array by Increasing Frequency.cpp, Ayush-Gupta/414. Third Maximum Number.cpp
=> 1636. Sort Array by Increasing Frequency

Ayush-Gupta/986. Interval List Intersections.cpp
LeetCode Problem Link: https://leetcode.com/problems/interval-list-intersections/
=> 986. Interval List Intersections

Ayush-Gupta/77. Combinations.cpp, Ayush-Gupta/896. Monotonic Array.cpp
=> 77. Combinations

Ayush-Gupta/47. Permutations II.cpp
LeetCode Problem Link: https://leetcode.com/problems/permutations-ii/
=> 47. Permutations II

.vscode/settings.json, Vindeep-Chaudhari/131_Palindrome_Partitioning.cpp, Vindeep-Chaudhari/22_Generate_Parentheses.cpp, Vindeep-Chaudhari/301_Remove_Invalid_Parentheses.cpp, Vindeep-Chaudhari/784_Letter_Case_Permutation.cpp
784. Letter Case Permutation - https://leetcode.com/problems/letter-case-permutation/
131. Palindrome Partitioning - https://leetcode.com/problems/palindrome-partitioning/
22. Generate Parentheses - https://leetcode.com/problems/generate-parentheses/
301. Remove Invalid Parentheses - https://leetcode.com/problems/remove-invalid-parentheses/
=> Vindeep: 784. Letter Case Permutation, 131. Palindrome Partitioning, 22. Generate Parentheses, 301. Remove Invalid Parentheses

Ayush-Gupta/338. Counting Bits.cpp
LeetCode Problem Link: https://leetcode.com/problems/counting-bits/
TC - O(n) | SC - O(n)
=> 338. Counting Bits

Vindeep-Chaudhari/136_Single_Number.cpp, Vindeep-Chaudhari/190_Reverse_Bits.cpp, Vindeep-Chaudhari/191_Number_of_1_Bits.cpp, Vindeep-Chaudhari/338_Counting_Bits.cpp
338. Counting Bits - https://leetcode.com/problems/counting-bits/
191. Number of 1 Bits - https://leetcode.com/problems/number-of-1-bits/
190. Reverse Bits - https://leetcode.com/problems/reverse-bits/
136. Single Number -https://leetcode.com/problems/single-number/
=> Vindeep: 191. Number of 1 Bits, 338. Counting Bits, 190. Reverse Bits, 136. Single Number

Vindeep-Chaudhari/1025_Divisor_Game.cpp, Vindeep-Chaudhari/118_Pascal's_Triangle.cpp, Vindeep-Chaudhari/1638_Count_Substrings_That_Differ_by_One_Character.cpp, Vindeep-Chaudhari/1641_Count_Sorted_Vowel_Strings.cpp, Vindeep-Chaudhari/1884_Egg_Drop_With_2_Eggs_and_N_Floors.cpp, Vindeep-Chaudhari/70_Climbing_Stairs.cpp
1884. Egg Drop With 2 Eggs and N Floors : https://leetcode.com/problems/egg-drop-with-2-eggs-and-n-floors/
1025. Divisor Game: https://leetcode.com/problems/divisor-game/
118. Pascal's Triangle: https://leetcode.com/problems/pascals-triangle/
70. Climbing Stairs: https://leetcode.com/problems/climbing-stairs
=> Vindeep: 1884. Egg Drop With 2 Eggs and N Floors, 118. Pascal's Triangle, 1025. Divisor Game, 70. Climbing Stairs

.vscode/settings.json, Vindeep-Chaudhari/198_House_Robber.cpp, Vindeep-Chaudhari/278_First_Bad_Version.cpp
278. First Bad Version - https://leetcode.com/problems/first-bad-version/
198. House Robber - https://leetcode.com/problems/house-robber/
=> Vindeep:  278. First Bad Version, 198. House Robber

Ravi-Teja/AddtoArray-formofInteger.cpp, Ravi-Teja/CountSortedVowelsStrings.cpp, Ravi-Teja/CountingBits.cpp, Ravi-Teja/DecodeWays.cpp, Ravi-Teja/DivisorGame.cpp, Ravi-Teja/IntersectionofTwoArrays.cpp, Ravi-Teja/ReverseBits.cpp, Ravi-Teja/SingleNumber.cpp, Ravi-Teja/SumOfAllSubsetsXORTotals.cpp, Ravi-Teja/TheDiningPhilosophers.cpp
- Single Number
- Sum of All Subsets XOR Totals
- The Dining Philosophers
- Divisor Game
- Climbing Stairs
- Count Differ Substring
- Count Sorted Vowel Strings
- Decode Ways
- Array-form of Integer
- Intersection of Two Arrays
=> Added solutions to 11 problems

Vindeep-Chaudhari/1646_Get_Maximum_in_Generated_Array.cpp, Vindeep-Chaudhari/213_House_Robber_II.cpp, Vindeep-Chaudhari/337_House_Robber_III.cpp, Vindeep-Chaudhari/838_Push_Dominoes.cpp
House Robber II : https://leetcode.com/problems/house-robber-ii/
House Robber III : https://leetcode.com/problems/house-robber-iii/
Push Dominoes : https://leetcode.com/problems/push-dominoes/
Get Maximum in Generated Array : https://leetcode.com/problems/get-maximum-in-generated-array/
=> Vindeep: House Robber II, House Robber III, Push Dominoes, Get Maximum in Generated Array

.vscode/settings.json, Vindeep-Chaudhari/1137_N-th_Tribonacci_Number.cpp, Vindeep-Chaudhari/1313_Decompress_Run-Length_Encoded_List.cpp, Vindeep-Chaudhari/392_Is_Subsequence.cpp, Vindeep-Chaudhari/45_Jump_Game_II.cpp, Vindeep-Chaudhari/55_Jump_Game.cpp, Vindeep-Chaudhari/72_Edit_Distance.cpp
Decompress Run-Length Encoded List : https://leetcode.com/problems/decompress-run-length-encoded-list/
Is Subsequence : https://leetcode.com/problems/is-subsequence/
Jump Game : https://leetcode.com/problems/jump-game/
Jump Game II : https://leetcode.com/problems/jump-game-ii/
=> Vindeep : Decompress Run-Length Encoded List, Is Subsequence, Jump Game, Jump Game II

Vindeep-Chaudhari/1043_Partition_Array_for_Maximum_Sum.cpp, Vindeep-Chaudhari/1524_Number_of_Sub-arrays_With_Odd_Sum.cpp, Vindeep-Chaudhari/474_Ones_and_Zeroes.cpp, Vindeep-Chaudhari/647_Palindromic_Substrings.cpp
Palindromic Substrings: https://leetcode.com/problems/palindromic-substrings/
Partition Array for Maximum Sum: https://leetcode.com/problems/partition-array-for-maximum-sum
Ones and Zeroes: https://leetcode.com/problems/ones-and-zeroes/
=> Vindeep : Palindromic Substrings, Partition Array for Maximum Sum, Ones and Zeroes

Vindeep-Chaudhari/494_Target_Sum.cpp, Vindeep-Chaudhari/623_Add_One_Row_to_Tree.cpp
Add One Row to Tree : https://leetcode.com/problems/add-one-row-to-tree/
Target Sum : https://leetcode.com/problems/target-sum/
=> Vindeep : Add One Row to Tree, Target Sum

.vscode/settings.json, Vindeep-Chaudhari/1981_Minimize_the_Difference_Between_Target_and_Chosen_Elements.cpp, Vindeep-Chaudhari/39_Combination_Sum.cpp, Vindeep-Chaudhari/56_Merge_Intervals.cpp, Vindeep-Chaudhari/62_Unique_Paths.cpp
Combination Sum : https://leetcode.com/problems/combination-sum/
Unique Paths : https://leetcode.com/problems/unique-paths/
=> Vindeep : Combination Sum, Unique Paths

Vindeep-Chaudhari/1389_Create_Target_Array_in_the_Given_Order.cpp, Vindeep-Chaudhari/139_Word_Break.cpp, Vindeep-Chaudhari/207_Course_Schedule.cpp, Vindeep-Chaudhari/219_Contains_Duplicate_II.cpp, Vindeep-Chaudhari/547_Number_of_Provinces.cpp
Word Break : https://leetcode.com/problems/word-break/
Number of Provinces : https://leetcode.com/problems/number-of-provinces/
Create Target Array in the Given Order : https://leetcode.com/problems/create-target-array-in-the-given-order/
=> Vindeep :  Word Break, Number of Provinces, Create Target Array in the Given Order

Dhairyashil-Shinde/57. Pascal Triangle.cpp, Dhairyashil-Shinde/58. Rotated Digits.cpp, Dhairyashil-Shinde/59. Target Sum.cpp, Dhairyashil-Shinde/60. Unique Paths.cpp, Dhairyashil-Shinde/61. Word Break.cpp, Dhairyashil-Shinde/62. Word Break-II.cpp, Dhairyashil-Shinde/63. Find a valid format for an alien dictionary.cpp, Dhairyashil-Shinde/64. Binary Watch.cpp, Dhairyashil-Shinde/65. Deep copy a graph.cpp, Dhairyashil-Shinde/66. Find if there exists a valid course schedule.cpp, Dhairyashil-Shinde/67. Find a valid course schedule.cpp, Dhairyashil-Shinde/68. Employee Importance.cpp, Dhairyashil-Shinde/69. Find Center Of Graph.cpp, Dhairyashil-Shinde/70. Find If Path Exists.cpp, Dhairyashil-Shinde/71. Find Town Judge.cpp
=> Day 52/300. And Happy Diwali Admin!

Dhairyashil-Shinde/72. Keys And Rooms.cpp, Dhairyashil-Shinde/73. Minimum Vertices To Nodes.cpp, Dhairyashil-Shinde/74. Reorder Routes to Make All Paths Lead to the City Zero2.cpp, Dhairyashil-Shinde/75. Calculate the minimum network delay.cpp, Dhairyashil-Shinde/76. Number of Provinces.cpp, Dhairyashil-Shinde/77. All Paths From Source to Target.cpp, Dhairyashil-Shinde/78. Reconstruct Itinerary.cpp, Dhairyashil-Shinde/79. Letter Tile Possibilities.cpp, Dhairyashil-Shinde/80. Can Place Flowers.cpp, Dhairyashil-Shinde/81. Maximum Score.cpp, Dhairyashil-Shinde/82. Find the container with the maximum water.cpp, Dhairyashil-Shinde/83. Best Time To Buy And Sell Stocks.cpp, Dhairyashil-Shinde/84. Maximum Swap.cpp, Dhairyashil-Shinde/85. Maximum Units on a Truck.cpp
=> Day 65/300.
